#+DATE: [2012-11-26 星期一 02:36]
#+POSTID: 160
#+BLOG: wuyao721
#+OPTIONS: toc:nil ^:nil
#+CATEGORY: emacs
#+TAGS: emacs, org-mode
#+PERMALINK: emacs-org-mode-pdf
#+LaTeX_CLASS: cjk-article
#+TITLE: Emacs Org-mode 制作PDF文档

Emacs Org 是什么，这里就不介绍了。

记得前不久我还用muse做笔记的，而现在就要用org，还是相当的纠结的。制作PDF最烦的就是中文显示了，周六用一整天折腾，终于搞定，现将过程记录下来。（仅在windows下测试通过，linux还未测试。）

本文只关注于使用Emacs Org生成PDF文档（尤其是中文显示问题），并假设读者对Emacs以及Emacs Org有一定的了解。

#+html: <!--more--> 

* 工具包

** Linux(Emacs + texlive + gbk2uni)
除了Emacs之外，还要安装texlive，它是Latex在Linux下的一个发行版，我们要用到它的一个程序pdflatex，用它将tex文件转成pdf。在ubuntu下这样安装：
#+begin_example
sudo apt-get install emacs23 texlive-latex-recommended latex-cjk-chinese
#+end_example

** Windows(Emacs + MinGW + [[http://www.ctex.org/][CTeX]] + gbk2uni)
CTeX是Latex在Windows下的一个发行版，同样的，它提供了程序pdflatex。

MinGW是GNU在Winodws下的一个发行版，我们要用到它的一个程序iconv。如果字符编码是GBK，就不用iconv了。


* 把org给黑了
既然org-mode没有考虑中文问题，那么只能黑它一下了。[fn:1]
可以到 [[https://github.com/wuyao721/51dotemacs]] 下载到这个文件 [[https://github.com/wuyao721/51dotemacs/blob/master/.emacs.d/elisp/org-latex-hack.el][org-latex-hack.el]] ，以下是具体内容。
** 添加新的latex文档类型
latex默认的文档类型有article, report, book和beamer，我们这里要新建一个支持中文的article，叫cjk-article，这个类型里，我们不使用默认的latex package（也就是org-export-latex-default-packages-alist），而使用自己定义的latex package（也就是org-export-latex-packages-alist）。
#+begin_example
(add-to-list 'org-export-latex-classes
		  '("cjk-article"
		    "\\documentclass{article}
 [NO-DEFAULT-PACKAGES]
 [PACKAGES]
 [EXTRA]"
         ("\\section{%s}" . "\\section*{%s}")
         ("\\subsection{%s}" . "\\subsection*{%s}")
         ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
         ("\\paragraph{%s}" . "\\paragraph*{%s}")
         ("\\subparagraph{%s}" . "\\subparagraph*{%s}")))
#+end_example

** 自定义latex package
上面说到，要用自定义latex package，那么它是怎样的呢，请看：
#+begin_example
(setq org-export-latex-packages-alist '(
    (""   "CJK"   t)
    (""     "indentfirst"  nil)
    ("pdftex"     "graphicx"  t)
    (""     "fancyhdr" nil)
    ("CJKbookmarks=true"     "hyperref"  nil)
"%% Define a museincludegraphics command, which is
%%   able to handle escaped special characters in image filenames.
\\def\\museincludegraphics{%
  \\begingroup
  \\catcode`\\\|=0
  \\catcode`\\\\=12
  \\catcode`\\\#=12
  \\includegraphics[width=0.75\\textwidth]
}"))
#+end_example

考察上面的配置，我们关注两个要点：latex包CJK提供了中文支持，CJKbookmarks=true让中文书签得以显示。这样生成的tex文件就大概是下面的样子：
#+begin_example
\usepackage{CJK}
\usepackage{indentfirst}
\usepackage[pdftex]{graphicx}
\usepackage{fancyhdr}
\usepackage[CJKbookmarks=true]{hyperref}
#+end_example

** 重定义生成pdf的命令
用pdflatex生成的pdf书签会有乱码问题，使用gbk2uni能解决这个问题。流程大概是这样的：
 1. pdflatex生成乱码书签的pdf
 2. iconv将utf-8格式的书签文本（也就是.out文件）转成gbk格式
 3. gbk2uni将书签文本转成指定格式
 4. pdflatex使用正确的书签文本生成没有乱码书签的pdf


如果org文件的格式是GBK，那么就不用第二步了。
#+begin_example
(setq org-latex-to-pdf-process
  '("pdflatex -interaction nonstopmode -output-directory %o %f"
    "iconv -f utf-8 -t gbk %b.out > %b.out.bak"
    "mv %b.out.bak %b.out"
    "gbk2uni %b.out"
    "pdflatex -interaction nonstopmode -output-directory %o %f"
    "rm %b.out.bak %b.tex"))
#+end_example

** 其它的小小改动
到目前为止，生成的tex文件头部分已经没有问题了，下面就要解决正文的问题。生成的tex文件正文必须是这样的：
#+begin_example
\begin{document}
\begin{CJK*}{UTF8}{gbsn}
.....
\end{CJK*}
\end{document}
#+end_example

参考函数org-export-latex-make-header和org-export-as-latex，我们可以看到要插入=\begin{CJK*}{UTF8}{gbsn}=这样的tex代码的正确的位置，还是比较麻烦的。[fn:2] 所以，我们要对这两个函数做小小的修改。（修改的el配置在后面贴出）



* 写作 & 发布
接下来就继续我们的org-mode写作，记得在 *.org* 文件里指明使用的文档风格：
: #+LaTeX_CLASS: cjk-article
这里的风格 *cjk-article* 在列表 *org-export-latex-classes* 可以找到。

在 *org-mode* 里用快捷键 *C-c C-e p* 将文本发布成pdf文档。


* 注意要点
如果你怎么整都是乱码的pdf，那么考虑以下几点

  - 字符编码是否一致
     看看是否把org文件保存成了GBK格式，而配置里却用了UTF-8。

  - 分步实现
     试试先生成tex文件，再用命令pdflatex生成pdf。这样能帮你发现问题所在。

  - emacs能否调用pdflatex,mv等命令
     设置好环境变量，确保emacs能调用到这些命令


* 未解问题
有一些未解问题，请高手指点

  - 示例超出pdf界限
      以下的示例生成的pdf超出界限，怎么办呢？
      #+begin_example
      apt-get install texlive-latex-base texlive-latex-recommended latex-cjk-chinese latex-cjk-chinese latex-cjk-chinese 
      #+end_example

  - pdf超链接有红色框框
      pdf超链接有红色框框，这样的显示效果不怎么好。怎么办？


* 参考资料
 - http://orgmode.org/manual/LaTeX-and-PDF-export.html
 - http://orgmode.org/worg/org-tutorials/org-latex-export.html
 - http://orgmode.org/worg/org-contrib/babel/examples/article-class.html
 - http://blog.csdn.net/ywj1225/article/details/7407316
 - http://comments.gmane.org/gmane.emacs.orgmode/52201


#+begin_quote
转载请注明出处：[[http://www.wuyao721.com/emacs-org-mode-pdf.html]]
#+end_quote


* Footnotes

[fn:1] 网上好像是说xelatex可以解决utf-8的问题，但是我真的不知道该怎么整。

[fn:2] 参考http://blog.csdn.net/ywj1225/article/details/7407316 和 http://comments.gmane.org/gmane.emacs.orgmode/52201

