#+DATE: [2012-11-23 星期五 13:59]
#+TITLE: Org2blog Readme
#+Options: num:nil
#+STARTUP: odd
#+Style: <style> h1,h2,h3 {font-family: arial, helvetica, sans-serif} </style>

* 概况
  org2blog/wp 是一个发布工具，它能将 Emacs 的 org-mode 文档发布到
  [[http://wordpress.org/][WordPress]] 博客.  org2blog/wp 是 org2blog 的其中一个软件包。
  另外一个是 [[http://tehom-blog.blogspot.com/][Tom Breton]] 的 [[http://repo.or.cz/r/org2blog.git/][org2blog/atom]] .

  从设计上讲， org2blog/wp 能够运行于任意支持 xml-rpc 的平台，
  但是实际上有一些 wordpress 特性 没有正常运行.

  org2blog 灵感来于并且基于 [[http://paste.lisp.org/display/69993][wordpress posting client for
  muse-mode]] ， 他的作者是 [[http://www.emacswiki.org/emacs/AshishShukla][Ashish Shukla]] .

  org2blog 授权于 GPLv3

* 安装

  从 GitHub 或者 Marmalade 上 下载 org2blog 

  : git clone http://github.com/punchagan/org2blog.git

  : http://marmalade-repo.org/packages/org2blog

  将 org2blog 的目录 加入 emacs 配置的 load path

  : (setq load-path (cons "~/.emacs.d/org2blog/" load-path))
  : (require 'org2blog-autoloads)

*** 依赖
    1. org2blog 依赖于 /xml-rpc/ （可以在 [[http://launchpad.net/xml-rpc-el][Launchpad]] 上找到）。  
       先将它也加入 /load-path/。

    2. 确认您安装了最新的 org-mode 。 org2blog支持 版本号大于7的 org-mode，
       但最好还是拿最新 org-mode。

* 使用方法
*** org2blog配置

    *Note* - This setup works only for org2blog version >=0.3. For
     lower versions of org2blog check the README from the commit
     e37126e

    您应该先告诉 org2blog 您的博客地址、用户名，以及一些可选的属性。
    实际上只要设置 =org2blog/wp-blog-alist= 的值就可以了。

    例子如下:
    : (setq org2blog/wp-blog-alist
    :       '(("wordpress"
    :          :url "http://username.wordpress.com/xmlrpc.php"
    :          :username "username"
    :          :default-title "Hello World"
    :          :default-categories ("org2blog" "emacs")
    :          :tags-as-categories nil)
    :         ("my-blog"
    :          :url "http://username.server.com/xmlrpc.php"
    :          :username "admin")))

    以上定义了两个博客分别是 =wordpress= 和 =my-blog= 。
    =url= and =username= 是必填的，其它是可选的. 

    您也可以使用 =.netrc= 文件来保存用户名和密码。

    您的 =.netrc= 看起来应该是这样的：

    : machine myblog login myusername password myrealpassword

    这样，您的 =dot emacs= 要这么写：

    : (setq blog (netrc-machine (netrc-parse "~/.netrc") "myblog" t))
    : (setq org2blog/wp-blog-alist
    :       '(("my-blog"
    :          :url "http://username.server.com/xmlrpc.php"
    :          :username (netrc-get blog "login")
    :          :password (netrc-get blog "password"))))


    可以通过 =customize group function= 查看或者自定义其它变量。

    : M-x customize-group org2blog/wp RET

*** 登录博客
    使用命令 *M-x org2blog/wp-login* ， org2blog 会询问您登录 
    =org2blog/wp-blog-alist= 里的哪个博客，然后询问您的密码。
    与其对应的命令是 *M-x org2blog/wp-logout*, 用于登出博客。

*** 写一篇新文章
    使用命令 *M-x org2blog/wp-new-entry*.
     - 多个 =标签= 或 =类别= 用英文逗号或空格分开.
       用 *C-c t* 补全标签或类别，添加新类别时会有提示。
     - 在 =#+DESCRIPTION= 后填写文章摘录
     - 在 =#+PERMALINK= 后填写文章链接
     - 在 =#+PARENT= 后填写文章的父文章，用 *C-c t* 也可以补全页面名称。

*** 发布模版
    通过修改变量 =org2blog/wp-buffer-template= 
    和函数 =org2blog/wp-buffer-format-function= 来自定义发布模版。
    
    例子如下：

    : (setq org2blog/wp-buffer-template
    :  "-----------------------
    : #+TITLE: %s
    : #+DATE: %s
    : -----------------------\n")
    :
    : (defun my-format-function (format-string)
    :    (format format-string
    :            org2blog/wp-default-title
    :            (format-time-string "%d-%m-%Y" (current-time)))))
    : (setq org2blog/wp-buffer-format-function 'my-format-function)

    这样用命令 =org2blog/wp-new-entry= 可以创建使用模版的文章，它有着默认的标题和时间。

*** 更新一篇现成的文章
    想要更新一篇现在的文章, 您只需要把文章改成你要的样子，然后用 ~org2blog~ 发布。
    通常 =POSTID= 已经保存在文件里，它用来确保你发布的是这一篇文章，而不是新的一篇。

*** 发布指令
    | 发布文章（作为草稿）     | *C-c d* | *M-x     org2blog/wp-post-buffer*         |
    | 发布文章                 | *C-c p* | *C-u M-x org2blog/wp-post-buffer*         |
    | 发布文章（作为页面草稿） | *C-c D* | *M-x     org2blog/wp-post-buffer-as-page* |
    | 发布文章（作为页面草稿） | *C-c P* | *C-u M-x org2blog/wp-post-buffer-as-page* |

*** 发布已有的org文档
    - 添加这些指令到文件里 =#+TITLE=, =#+OPTIONS=, =#+TAGS=, =#+CATEGORY=,
          =#+DESCRIPTION=, =#+DATE=,   (全部都是可选的）
    - 添加 =#+POSTID= 到一个已经发布的文件
    - 使用上面说到的发布指令发表文章
*** 发布一个子树
    - 使用指令 *M-x org2blog/wp-post-subtree*.
    - 子树的标签会成为文章的标签
    - Other properties can be set using a property drawer.  The
      properties use the same names as the buffer variables.
    - =POST_DATE= sets the date to be used for the post. If it is not
      present, =SCHEDULED=, =DEADLINE= or any other active or inactive
      time-stamps are used.
    - The headline is used as the title of the post. But, =TITLE= can
      be used to use a different title.
*** Posting source code blocks
    Babel source blocks or example code is automatically posted in
    =<pre>= tags.  You can ask =org2blog= to use Wordpress's
    sourcecode shortcode blocks.  To use this, you need to set the
    variable =org2blog/wp-use-sourcecode-shortcode= and also add
    =htmlize.el= (available in org-mode's =contrib/lisp=) to your
    =load-path=.  Wordpress's sourcecode shortcode blocks can be given
    various [[http://en.support.wordpress.com/code/posting-source-code/#configuration-parameters][configuration parameters]].  These can be passed to the
    exported sourcecode shortcode blocks, by passing them to the babel
    blocks using =:syntaxhl= parameter.  You could also modify the
    default arguments passed to sourcecode shortcode blocks by
    customizing the =org2blog/wp-sourcecode-default-params= variable.
*** Delete an entry or a page
    - If you are in the buffer of the entry/page, with =#+POSTID=
      present on the page, use:

      *M-x org2blog/wp-delete-entry* or *M-x  org2blog/wp-delete-page*

    - If you want to delete a particular post (whose post-id is known)
      from any buffer, use

      *C-u post-id M-x org2blog/wp-delete-entry*.

    Similarly, for a page.

*** Enabling org2blog mode (defines key-bindings)
    - use *M-x org2blog/wp-mode*.
      This defines the following the key-bindings:
      | *C-c p* | publish buffer                   |
      | *C-c d* | post as draft                    |
      | *C-c t* | complete tag or parent page name |

*** Uploading Images or Files
    In-line images and linked images (or files) with file:// urls will
    be uploaded to the media library and the links will be updated.
    Information about uploaded files is added as a comment to the post
    itself.

    Captions and attributes as [[http://orgmode.org/manual/Images-in-HTML-export.html][defined]] in org-mode will be preserved,
    but these attributes are not saved with the image to the library
    itself.

*** "Dashboard" of all posts
    ~org2blog~ makes it easy to manage your blog-posts by actually
    keeping track of all the posts you make from it, in a simple
    org-table.  By default it is saved in a file ~.org2blog.org~ in
    the ~org-directory~.  This is meant to be a dashboard of sorts,
    and is an optional feature that can be turned off.
* Miscellaneous
  1. You may want to look at the [[http://orgmode.org/manual/Export-options.html#Export-options][Export options]] and [[http://orgmode.org/manual/HTML-export.html#HTML-export][HTML export]]
     sections of the org-manual.

  2. If you wish to post to blogger from org-mode, look at -

     1. [[http://repo.or.cz/r/org2blog.git/][org2blog/atom]], a g-client extension by [[http://tehom-blog.blogspot.com/][Tom Breton]]

     2. [[http://github.com/rileyrg/org-googlecl][org-googlecl]] by Richard Riley -- uses [[http://code.google.com/p/googlecl/][googlecl]]

  3. Please go through the README and the FAQ, before writing to me.
     Also, looking at =M-x customize-group org2blog-wp= might help.

  4. If you have an issue/bug/feature request, use the issue tracker
     on git or drop a mail to punchagan+org2blog[at]gmail[dot]com.
     I'd also appreciate patches/suggestions to improve the
     documentation.  Feel free to drop in with general comments, too.
     I'd love to hear from you!  NOTE: If you are using the package
     from ELPA/Marmalade, please try using the latest =git= version
     before filing a bug report.

  5. Feel free to add your site to the list of sites using org2blog,
     on the [[https://github.com/punchagan/org2blog/wiki/Blogs-using-org2blog][wiki]] at github.

* FAQ
  - How many blogs can I configure with org2blog?

    You can configure and use any number of blogs with org2blog/wp.
    Use the ~org2blog/wp-blog-alist~ variable to configure each blog.
    Look at the [[Defining your blog setup]] section, in the README.  But,
    note that you can be logged in, to just one blog at a time.

  - How do I change the default title of a new post?

    : (setq org2blog/wp-default-title "My New Title")

  - How do I change the default title for one blog alone?

    Set the relevant (~:default-title~) variable in the
    ~org2blog/wp-blog-alist~ variable.

  - I do not use tags. I wish to use them as categories. How?

    Setting the ~org2blog/wp-use-tags-as-categories~ variable will do
    that for all the blogs.

    : (setq org2blog/wp-use-tags-as-categories t)

    Instead, you can set the corresponding variable for each blog that
    you are using.

  - Can I configure org2blog to confirm before publishing a post?

    : (setq org2blog/wp-confirm-post t)

  - I wish to customize the default template of a new post. How do I
    do it?

    Customize the variable =org2blog/wp-buffer-template=.

  - New-lines are not handled properly. Why?

    The behaviour of new-lines has been working since a little before
    version 0.3.  It is highly recommended that you use the latest git
    version of org2blog.

    By default, new lines are stripped off from the org buffer.  To
    retain new-lines, unset the =org2blog/wp-keep-new-lines=
    variable.

  - Why aren't my SRC blocks not enclosed in =[sourcecode]
    [/sourcecode]=  block?

    Set the =org2blog/wp-use-sourcecode-shortcode= variable to turn on
    this behaviour.  You may also set it at a per-blog level, if you
    choose.

  - Is wordpress the only CMS/Blog-engine that org2blog/wp supports?

    Any blog engine using the metaweblog API should work,
    theoretically.  But, it is not tested with other blog engines.

    One happy user reports that org2blog [[https://github.com/punchagan/org2blog/issues/issue/37][also works]] with the [[http://www.doclear.net/][Dotclear]]
    weblog engine.

  - Is there a way to import from wordpress or other blogs into the
    org2blog post format?

    I've a simple [[https://github.com/punchagan/org2blog-importers/blob/master/wp_to_org2blog.py][python script]] that uses ~pandoc~ to convert from
    Wordpress export xml to org2blog posts.  It could easily be
    tweaked to write importers for other kinds of blogs.

  - How do I split a post into an introductory paragraph and a full
    view.

    Just put in

    : #+HTML: <!--more-->

    at the location where you wish to split the post.
