#+BLOG: wuyao721
#+POSTID: 531
#+DATE: [2013-12-15 星期日 18:38]
#+OPTIONS: toc:nil ^:nil 
#+CATEGORY: emacs
#+PERMALINK: emacs-win-shell-buffer
#+TAGS: emacs
#+LaTeX_CLASS: cjk-article
#+DESCRIPTION:
#+TITLE: emacs win32缓存shell输出

windows下的emacs问题很多。其中一个很让人纠结的事情就是emacs shell缓存，也就是我们看不到shell里交互程序的输出。

#+html: <!--more--> 

* 问题出在哪里？
我一直都没能搞清楚问题出在哪里，知道我无意中看到这篇 [[http://www.gnu.org/software/emacs/manual/html_mono/efaq-w32.html][GNU Emacs FAQ for MS Windows]] ，引用里面的原文：
#+BEGIN_QUOTE
Although it may at first seem like the shell is buffering the output from the program, it is actually the program that is buffering output. The C runtime typically decides how to buffer output based upon whether stdout is bound to a handle to a console window or not. If bound to a console window, output is buffered line by line; if bound to a block device, such as a file, output is buffered block by block.
#+END_QUOTE

简单来说，没输出是因为被shell里子程序缓存了，而这是windows的机制决定的：输出如果是指向console，那么以行输出；如果指向block，那么以块输出。很明显输出到emacs shell是以block的形式。

* 解决方案
好了，既然知道原因了，那么我们就能得出解决方法：在交互程序里修改缓存机制。虽然结果让人很失望。

** 自己的程序（C/C++）
在自己的程序里修改缓存机制：
: setvbuf (stderr, (char *)NULL, _IOLBF, 0);
: setvbuf (stdout, (char *)NULL, _IOLBF, 0);

** sqlite3
: sqlite3 -interactive

** mysql
: M-x sql-mysql
或者
: mysql -n

** python
: python -i
不过django本地测试就不行了，谁知道告诉我一下啊。
: manage.py runserver 9000

#+begin_quote
转载请注明出处：[[http://www.wuyao721.com/emacs-win-shell-buffer.html]]
#+end_quote
